config/routes.rb
Rails.application.routes.draw do
  resources :shipments
  resources :subscriptions
  get 'plans/show'
  get 'plans/index'

  ##### ROOT
  root 'home#show'

  ##### STATIC PAGES
  get 'static_pages/help', as: 'help'
  get 'static_pages/about', as: 'about'
  get 'static_pages/contact', as: 'contact'
  

  ##### USERS
  resources :users
  get 'signup' => 'users#new'
  resources :account_activations, only: [:edit]


  ##### SESSIONS  
  # Login
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create', as: 'create_login'

  # Logout
  delete '/logout' => 'sessions#destroy', as: 'logout'


  ##### BOXES + ITEMS3
  get '/boxes/new' => 'boxes#new'
  get '/boxes/:id', to: 'boxes#show'
  
  
  resources :boxes do
    resources :items
  end
  
  ##### ITEMS
  
  get 'items/new' => 'items#new'

  ##### PLANS
  get 'plans/:id' => 'plans#show', as: 'plan'
  get 'plans/' => 'plans#index'

  ##### SUBSCRIPTION MODIFICATION EMANCIPATION PROCLAMATION
  get 'subscriptions/:id/upgrade' => 'subscriptions#upgrade', as: 'upgrade'
  get 'subscriptions/:id/downgrade' => 'subscriptions#downgrade', as: 'downgrade'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token #for tokens, obvies
  before_save   :downcase_email
  before_create :create_activation_digest
  
  has_many :subscriptions
  has_many :plans, through: :subscriptions
  
  has_many :shipments
  has_many :boxes, through: :shipments

  #################### CALLBACKS ####################
  before_save { self.email = email.downcase }

  #################### VALIDATIONS ####################
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, length: { maximum: 50 }
  
  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email, 
    presence: true, 
    length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }

  #################### pw handling ####################  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  #allow_nil is ok bc has_secure_password has a separate validation system
  
  #################### other ####################    
  def User.digest(string)
    #switch to decide whatever value populates the computational cost variable, then put it in
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


  #rtn random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  
  def remember  #for actuating "remember me"
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
   
   
  #forget that usey mcuser
  def forget #called by sessions helper
    update_attribute(:remember_digest, nil)
  end
  
  
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end  
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]  #make sure logged in to see these pgs
  before_action :correct_user,   only: [:edit, :update]  #make sure user A can't edit user B
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end


  def show
    @user = User.find(params[:id])
    @user_subs = @user.subscriptions
    
    #Plan.find(myUser.subscriptions.first.plan_id).name
  end


  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else #if writing the user to the db just is not happening that day...reload form
      render 'new'
    end
  end


  def edit
    #binding.pry
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      #handle successfulness of your update here
      flash[:success] = "Your profile is updated! Purrfect!"
      redirect_to @user
    else
      render 'edit'
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  
############  
  private
    def user_params
      #binding.pry
      params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
    end
    
    ###before filters
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Uh, quick paws: You need to be logged in to do that!"
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms user adminnyness
    def admin_user
      redirect_to(root_url) unless current_user.is_admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

  def is_admin?
    current_user.is_admin == true
  end

end

app/views/users/_new_form.html.erb
<%= form_for @user, url: users_path do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        The following errors prevented this user from saving:
      </h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Name: <br> <%= f.text_field :name %> <br> <br>
  Email: <br> <%= f.text_field :email %> <br> <br>
  Password <em>(minimum 6 char)</em>: <br> <%= f.password_field :password %> <br> <br>
  Password Confirmation: <br> <%= f.password_field :password_confirmation %> <br> <br>
  <%= f.submit("Create!", class: 'btn btn-dark btn-circle btn-lg') %> <br>
<% end %>

app/views/users/_user.html.erb
<li>
  <!-- see 9.4.1 if you want gravatar code. wanted to save space/loadtime/privacy -->
  <%= link_to user.username, user %>
  <% if current_user.is_admin? && !current_user?(user) %> | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure you want to remove that user?" } %>
  <% end %>
</li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'User Directory') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      
      <% if @plan_signup %>
        You're starting off with the <%= @plan_signup.name %> plan!
        <%= f.hidden_field :plan_id, value: @plan_signup.id %>
      <% end %>

<h2>      [SIMULATED NOTIONAL SUPER MAKE BELIEVE CREDIT CARD INFO FORM GOES HERE IN OUR IMAGINATION] </h2>


      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3><%= @user.username %></h3><br><br>


<% provide(:title, @user.username) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.username %>
            </h1>
        </section>
    </aside>
</div>
<h4>
First Name: <i><%= @user.first_name %> </i><br>
Last Name: <i><%= @user.last_name %> </i><br>
Contact: <i><%= @user.email %> </i><br>
Email confirmed: <i><%= @user.activated %> </i><br>
Account type: 
  <% if @user.is_admin %>
    <font color="#cc3333"><i>Administrator </i></font><br>
  <% else %>
    <i>Regular User</i><br>
  <% end %>
</h4>
<hr>
<h3><%= @user.username %>'s current subscription data:</h3>
<ul>
<% @user_subs.each do |subscription| %>
  <li>
    <p>Started Subscription #<%= subscription.id %> on <%= Plan.find(subscription.plan_id).created_at %></p>
    <p>As of <%= Plan.find(subscription.plan_id).updated_at %>, this subscription is set for <%= Plan.find(subscription.plan_id).name %> @ $<%= Plan.find(subscription.plan_id).price %> / mo </p>
    
    <% if (subscription.plan_id < 3) %> <%= link_to 'UPGRAYEDD', upgrade_path(subscription) %> <% end %> 
    <% if (subscription.plan_id > 1) %> <%= link_to 'DOWNGRADE', downgrade_path(subscription) %> <% end %>
    <p><font color="#FF0000"><%= link_to 'Unsubscribe from this subscription',  subscription,  method: :delete, data: { confirm: 'Are you sure?' } %></font></p>
  </li>
<% end %>
</ul>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>