config/routes.rb
Rails.application.routes.draw do
  resources :shipments
  resources :subscriptions
  get 'plans/show'
  get 'plans/index'

  ##### ROOT
  root 'home#show'

  ##### STATIC PAGES
  get 'static_pages/help', as: 'help'
  get 'static_pages/about', as: 'about'
  get 'static_pages/contact', as: 'contact'
  

  ##### USERS
  resources :users
  get 'signup' => 'users#new'
  resources :account_activations, only: [:edit]


  ##### SESSIONS  
  # Login
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create', as: 'create_login'

  # Logout
  delete '/logout' => 'sessions#destroy', as: 'logout'


  ##### BOXES + ITEMS3
  get '/boxes/new' => 'boxes#new'
  get '/boxes/:id', to: 'boxes#show'
  
  
  resources :boxes do
    resources :items
  end
  
  ##### ITEMS
  
  get 'items/new' => 'items#new'

  ##### PLANS
  get 'plans/:id' => 'plans#show', as: 'plan'
  get 'plans/' => 'plans#index'

  ##### SUBSCRIPTION MODIFICATION EMANCIPATION PROCLAMATION
  get 'subscriptions/:id/upgrade' => 'subscriptions#upgrade', as: 'upgrade'
  get 'subscriptions/:id/downgrade' => 'subscriptions#downgrade', as: 'downgrade'
  
end

app/models/box.rb
class Box < ActiveRecord::Base
  validates :theme, :presence => true, :length => { :minimum => 2 }
  validates :subscription_level,  :presence => true
  validates :month, :presence => true
  validates :year, :presence => true

  has_many :box_items
  has_many :items, through: :box_items
  
  accepts_nested_attributes_for :items
  
  # def items_attributes=(item_attributes)
  #   item_attributes.values.each do |item_attribute|
  #     item = Item.find_or_create_by(item_attribute)
  #     self.items << item
  #   end
  # end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create, :edit, :update, :destroy]  #make sure logged in to see these pgs
  before_action :admin_user,     only: [:index, :new, :create, :edit, :update, :destroy]
  
  def index
    #show all boxes statuses
    @boxes = Box.paginate(page: params[:page])
  end


  def show
    @user = current_user #for conditional "ship this box" button for admins
    @box = Box.find(params[:id])
    @plan = Plan.find(@box.subscription_level)
    @items = @box.items
  end


  def new
    ##build out objects to provide to form
    @box = Box.new
    
    3.times do
      @box.items << Item.new
    end
  end


  def create

    @box = Box.new
    @box.theme = params[:box][:theme]
    @box.subscription_level = params[:box][:subscription_level]
    @box.month = params[:box][:month]
    @box.year = params[:box][:year]
    
    # I KNOOOOOOOWWW THERES A MUCH BETTER WAY TO DO THIS IN ONE LINE BUT I JUST WANT IT WORKING FIRST
    (0..2).each do |num|
      if params[:box][:items_attributes][num.to_s][:title]
        @box.items << Item.new
        @box.items[num].title =         params[:box][:items_attributes][num.to_s][:title]
        @box.items[num].description =   params[:box][:items_attributes][num.to_s][:description]
        @box.items[num].image_url =     params[:box][:items_attributes][num.to_s][:image_url]
        @box.items[num].size =          params[:box][:items_attributes][num.to_s][:size]
        @box.items[num].buy_more_url =  params[:box][:items_attributes][num.to_s][:buy_more_url]
        #get this working then try @box.items[0].items_attributes = 
      end
    end

    if @box.save
      flash[:info] = "Box created!"
      redirect_to @box
    else #if writing the user to the db just is not happening that day...reload form
      flash[:warning] = "Oops, you missed a spot!"
      render 'new'
    end
  end


  def edit
    @box = Box.find(params[:id])
  end
  
  
  def update
  end


  def destroy
    Box.find(params[:id]).destroy
    flash[:success] = "Box deleted"
    redirect_to boxes_url
  end

  
  
  private
    # def box_params
    #   params.require(:box).permit(:theme, item_ids:[], item_attributes: [:title, :description, :image_url, :size, :buy_more_url])
    # end
    
    ###before filters
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Uh, quick paws: You need to be logged in to do that!"
        redirect_to login_url
      end
    end
    
    # Confirms user adminnyness
    def admin_user
      # unless @current_user.is_admin
      #   flash[:danger] = "Sorry, only Administrator accounts wield teh powerz teh create/modify/delete box3n!"
      #   redirect_to(box_url) unless @current_user.is_admin
      # end
    end
  
  
end

app/helpers/box_helper.rb
module BoxHelper
end

app/views/boxes/_box.html.erb
<li>
  <%= link_to box.theme, box %> | <%= link_to "delete", box, method: :delete,
                                  data: { confirm: "You sure you want to remove that box?" } %>
</li>

app/views/boxes/_form.html.erb
# app/views/box/_form.html.erb
 
<%= form_for box do |f| %>
  <%= f.label "Box" %>
  <%= f.text_field :title %>
  <%= f.label "Theme" %>
  <%= f.text_area :theme %>
  <%= f.collection_check_boxes :item_ids, Item.all, :id, :title %>
  <%= f.fields_for :items, box.items.build do |items_fields| %>
    <%= items_fields.text_field :title %>
    <%= items_fields.text_area :description %>
    <%= items_fields.text_field :image_url %>
    <%= items_fields.text_field :size %>
    <%= items_fields.text_field :buy_more_url %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/boxes/create.html.erb
<h1>Box#create</h1>
<p>Find me in app/views/box/create.html.erb</p>

app/views/boxes/destroy.html.erb
<h1>Box#destroy</h1>
<p>Find me in app/views/box/destroy.html.erb</p>

app/views/boxes/edit.html.erb
<h1>Box#edit</h1>
<p>Find me in app/views/box/edit.html.erb</p>

app/views/boxes/index.html.erb
<% provide(:title, 'Box Index') %>
<h1>All Boxes</h1>

<%= will_paginate %>

<ul class="boxes">
  <%= render @boxes %>
</ul>

<%= will_paginate %>

<% if is_admin? %>
  <%= link_to 'Create a New Box', new_box_path %>
<% end %>

app/views/boxes/new.html.erb
<% provide(:title, 'Create a new box') %>
<h1>Create a new box!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @box do |f| %>
      <%= f.label :theme %>
      <%= f.text_field :theme, class: 'form-control' %>

      <%= f.label :subscription_level %>

      <select name="box[subscription_level]">
        <% Plan.all.each do |plan| %>
          <option value="<%= plan.id %>"><%= plan.name %></option>
        <% end %>
      </select>


      <%= f.label :month %>
      <%= f.text_field :month, class: 'form-control' %>

      <%= f.label :year %>
      <%= f.text_field :year, class: 'form-control' %>
      <hr>
      
      <%= f.fields_for :items do |item| %>
        <%= item.label :title %>
        <%= item.text_field :title %>
        
        <%= item.label :description %>
        <%= item.text_field :description, class: 'form-control' %>
        <%= item.label :image_url %>
        <%= item.text_field :image_url, class: 'form-control' %>
        <%= item.label :size %>
        <%= item.text_field :size, class: 'form-control' %>
        <%= item.label :buy_more_url %>
        <%= item.text_field :buy_more_url, class: 'form-control' %>
      <% end %>

      <%= f.submit "Create my box", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boxes/show.html.erb
<h1>Box: <%= @box.theme %></h1>

<h4>What's inside the '<%= @box.theme %>' box:</h4>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.title, box_item_path(@box, item) %></li>
  <% end %>
</ul>
<% if current_user && current_user.is_admin? %>
  <%= link_to "Click to ship", new_shipment_path(@box, :box_id => @box.id, :box_plan => @box.subscription_level), data: { confirm: "For reals right? Cuz you sure as ship can't unship that ship." } %> to all <%= @plan.name %> subscribers!
<% end %>

app/views/boxes/update.html.erb
<h1>Box#update</h1>
<p>Find me in app/views/box/update.html.erb</p>