config/routes.rb
Rails.application.routes.draw do
  resources :shipments
  resources :subscriptions
  get 'plans/show'
  get 'plans/index'

  ##### ROOT
  root 'home#show'

  ##### STATIC PAGES
  get 'static_pages/help', as: 'help'
  get 'static_pages/about', as: 'about'
  get 'static_pages/contact', as: 'contact'
  

  ##### USERS
  resources :users
  get 'signup' => 'users#new'
  resources :account_activations, only: [:edit]


  ##### SESSIONS  
  # Login
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create', as: 'create_login'

  # Logout
  delete '/logout' => 'sessions#destroy', as: 'logout'


  ##### BOXES + ITEMS3
  get '/boxes/new' => 'boxes#new'
  get '/boxes/:id', to: 'boxes#show'
  
  
  resources :boxes do
    resources :items
  end
  
  ##### ITEMS
  
  get 'items/new' => 'items#new'

  ##### PLANS
  get 'plans/:id' => 'plans#show', as: 'plan'
  get 'plans/' => 'plans#index'

  ##### SUBSCRIPTION MODIFICATION EMANCIPATION PROCLAMATION
  get 'subscriptions/:id/upgrade' => 'subscriptions#upgrade', as: 'upgrade'
  get 'subscriptions/:id/downgrade' => 'subscriptions#downgrade', as: 'downgrade'
  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def show
    @plan = Plan.find(params[:id])
  end

  def index
    @plans = Plan.all
  end
  
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/index.html.erb
<h1>Plans, plans, plans!</h1>

<% @plans.each do |pl| %>
  <h2><%= link_to pl.name, plan_path(pl) %> / $<%= pl.price.to_i %> per month</h2>
<% end %>
<h6>[ &lt;&lt;&lt; <i><%= link_to "back to home", root_path %> </i>]</h6>

app/views/plans/show.html.erb
<% provide(:title, @plan.name) %>
<h1>"<%= @plan.name %>"</h1>
<h2>$<%= @plan.price.to_i %> per month</h2>
<br><br>
<h2><%= @plan.description %></h2>


<h2><%= link_to '[ select this plan ]', new_subscription_path(:@plan_level => @plan.id) %></h2>

<h6>[ &lt;&lt;&lt; <i><%= link_to "back to plans index", plans_path %> </i>]</h6>