config/routes.rb
Rails.application.routes.draw do
  resources :shipments
  resources :subscriptions
  get 'plans/show'
  get 'plans/index'

  ##### ROOT
  root 'home#show'

  ##### STATIC PAGES
  get 'static_pages/help', as: 'help'
  get 'static_pages/about', as: 'about'
  get 'static_pages/contact', as: 'contact'
  

  ##### USERS
  resources :users
  get 'signup' => 'users#new'
  resources :account_activations, only: [:edit]


  ##### SESSIONS  
  # Login
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create', as: 'create_login'

  # Logout
  delete '/logout' => 'sessions#destroy', as: 'logout'


  ##### BOXES + ITEMS3
  get '/boxes/new' => 'boxes#new'
  get '/boxes/:id', to: 'boxes#show'
  
  
  resources :boxes do
    resources :items
  end
  
  ##### ITEMS
  
  get 'items/new' => 'items#new'

  ##### PLANS
  get 'plans/:id' => 'plans#show', as: 'plan'
  get 'plans/' => 'plans#index'

  ##### SUBSCRIPTION MODIFICATION EMANCIPATION PROCLAMATION
  get 'subscriptions/:id/upgrade' => 'subscriptions#upgrade', as: 'upgrade'
  get 'subscriptions/:id/downgrade' => 'subscriptions#downgrade', as: 'downgrade'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <b>Meowbox</b>
    by Christopher Morrison
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MeowBox", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
          <li><%= link_to "Pick a Plan!", plans_path %></li>
        <% else %>
          <li><%= link_to "Add another plan!", plans_path %></li>
        <% end %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <% if is_admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <font color="#990000">Admin</font> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Subscriptions", subscriptions_path %></li>
                <li><%= link_to "Boxes", boxes_path %></li>
                <li><%= link_to "Shipments", shipments_path %></li>
                <li class="divider"></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Purrfile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>